import assert from "node:assert/strict";
import { PGlite } from "@electric-sql/pglite";
import { drizzle } from "drizzle-orm/pglite";
import { migrate } from "drizzle-orm/pglite/migrator";
import { eq } from "drizzle-orm";
import * as schema from "../lib/db/schema";
import { paymentSummary, reviewPlanPayment, submitPlanPayment } from "../features/payments/plan-payment-service";
import { listUserOrders, reviewVehicleOrder, submitVehicleOrder } from "../features/payments/vehicle-order-service";
import { receiptType } from "../features/payments/receipt";

const client = new PGlite();
const db = drizzle(client, { schema });
try {
  await migrate(db, { migrationsFolder: "./migrations" });
  const userId = crypto.randomUUID(), otherId = crypto.randomUUID(), adminId = crypto.randomUUID();
  for (const [id, role] of [[userId, "user"], [otherId, "user"], [adminId, "admin"]] as const) {
    await db.insert(schema.users).values({ id, name: role, email: `${id}@example.test`, role, passwordHash: "test-only", createdAt: new Date() });
  }
  const plan = (await db.select().from(schema.investmentPlans))[0];
  const method = (await db.select().from(schema.paymentMethods))[0];
  const screenshot = Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jYxkAAAAASUVORK5CYII=", "base64");
  assert.equal(receiptType(screenshot), "image/png");
  assert.equal(receiptType(Buffer.from("<svg onload='alert(1)'/>")), null);
  assert.equal(receiptType(Buffer.from("not-an-image")), null);
  const input = { id: crypto.randomUUID(), planId: plan.id, methodId: method.id, amount: plan.minInvestment, address: "DEMO-ADDRESS", screenshotKey: "receipts/test.png", screenshotType: "image/png" };
  await assert.rejects(submitPlanPayment(db, userId, input), /no longer available/);
  await db.update(schema.paymentMethods).set({ address: input.address }).where(eq(schema.paymentMethods.id, method.id));
  await assert.rejects(submitPlanPayment(db, userId, { ...input, amount: plan.minInvestment - 1 }), /investment limits/);
  await assert.rejects(submitPlanPayment(db, userId, { ...input, amount: (plan.maxInvestment ?? 100_000_000) + 1 }), /investment limits/);
  await assert.rejects(submitPlanPayment(db, userId, { ...input, address: "OLD-ADDRESS" }), /address has changed/);
  const id = await submitPlanPayment(db, userId, input);
  assert.equal(await submitPlanPayment(db, userId, input), id, "Retries must be idempotent");
  assert.equal(await submitPlanPayment(db, userId, { ...input, id: crypto.randomUUID() }), id, "Only one pending submission per plan");
  assert.equal((await paymentSummary(db, userId)).approvedAmount, 0);
  assert.equal((await paymentSummary(db, otherId)).payments.length, 0);
  await assert.rejects(submitPlanPayment(db, otherId, input), /Invalid submission/);
  assert.equal(await reviewPlanPayment(db, userId, id, "approved", ""), false, "Users cannot review payments");
  assert.equal(await reviewPlanPayment(db, adminId, id, "approved", "Verified demo screenshot"), true);
  assert.equal(await reviewPlanPayment(db, adminId, id, "approved", ""), false, "Approval cannot credit twice");
  assert.equal(await reviewPlanPayment(db, adminId, id, "rejected", ""), false, "Completed reviews cannot change");
  assert.equal((await paymentSummary(db, userId)).approvedAmount, input.amount);
  const rejectedId = await submitPlanPayment(db, userId, { ...input, id: crypto.randomUUID() });
  assert.equal(await reviewPlanPayment(db, adminId, rejectedId, "rejected", "Please upload a clear screenshot"), true);
  assert.equal((await paymentSummary(db, userId)).approvedAmount, input.amount, "Rejections must not affect balance");
  const resubmittedId = await submitPlanPayment(db, userId, { ...input, id: crypto.randomUUID() });
  assert.notEqual(resubmittedId, rejectedId, "Rejected payments can be resubmitted");
  await db.update(schema.paymentMethods).set({ address: "NEW-DEMO-ADDRESS" }).where(eq(schema.paymentMethods.id, method.id));
  await db.delete(schema.investmentPlans).where(eq(schema.investmentPlans.id, plan.id));
  const summary = await paymentSummary(db, userId);
  assert.equal(summary.approvedAmount, input.amount, "Editing or deleting a plan cannot erase approved balances");
  assert.ok(summary.payments.every(payment => payment.planName === plan.name && payment.address === input.address));
  assert.ok(summary.payments.every(payment => !("screenshotKey" in payment)), "Summary must not expose receipt storage keys");
  const receipt = await db.query.planPayments.findFirst({ where: eq(schema.planPayments.id, id) });
  assert.equal(receipt!.screenshotKey, input.screenshotKey);
  // Bank transfers: the payment keeps a readable copy of the account details, even after the bank is edited.
  const [otherPlan] = await db.insert(schema.investmentPlans).values({ id: crypto.randomUUID(), name: "Bank plan", tagline: "t", minInvestment: 100, maxInvestment: null, duration: "d", withdrawals: "w", riskLevel: "low", expectedReturn: "r", fee: "f", features: ["x"], createdAt: new Date(), updatedAt: new Date() }).returning();
  const [bank] = await db.insert(schema.paymentMethods).values({ id: crypto.randomUUID(), kind: "bank", name: "Demo Bank", network: "Bank transfer", address: "0123456789", accountName: "Demo Holder", routingNumber: "021000021", updatedAt: new Date() }).returning();
  const bankInput = { id: crypto.randomUUID(), planId: otherPlan.id, methodId: bank.id, amount: 250, address: "0123456789", screenshotKey: "receipts/bank.png", screenshotType: "image/png" };
  const bankId = await submitPlanPayment(db, userId, bankInput);
  await db.update(schema.paymentMethods).set({ address: "9999999999", accountName: "Someone Else" }).where(eq(schema.paymentMethods.id, bank.id));
  const bankPayment = (await paymentSummary(db, userId)).payments.find(payment => payment.id === bankId)!;
  assert.equal(bankPayment.network, "Bank transfer");
  assert.equal(bankPayment.methodName, "Demo Bank");
  assert.equal(bankPayment.address, "Demo Holder · Account 0123456789 · Routing 021000021");
  await assert.rejects(submitPlanPayment(db, otherId, { ...bankInput, id: crypto.randomUUID() }), /address has changed/);
  // Car orders: price comes from the listing, one pending order per car, admin review, no balance change.
  const car = (await db.select().from(schema.vehicles))[0];
  const orderInput = { id: crypto.randomUUID(), vehicleId: car.id, methodId: bank.id, address: "9999999999", screenshotKey: "orders/test.png", screenshotType: "image/png" };
  await assert.rejects(submitVehicleOrder(db, userId, { ...orderInput, vehicleId: "no-such-car" }), /no longer available/);
  await assert.rejects(submitVehicleOrder(db, userId, { ...orderInput, address: "OLD" }), /details have changed/);
  const orderId = await submitVehicleOrder(db, userId, orderInput);
  assert.equal(await submitVehicleOrder(db, userId, orderInput), orderId, "Order retries must be idempotent");
  assert.equal(await submitVehicleOrder(db, userId, { ...orderInput, id: crypto.randomUUID() }), orderId, "Only one pending order per car");
  await assert.rejects(submitVehicleOrder(db, otherId, orderInput), /Invalid submission/);
  const [myOrder] = await listUserOrders(db, userId);
  assert.equal(myOrder.price, car.price);
  assert.equal(myOrder.vehicleName, `${car.year} ${car.model} ${car.trim}`);
  assert.equal((await listUserOrders(db, otherId)).length, 0, "Orders are private to their owner");
  assert.ok(!("screenshotKey" in myOrder), "Order lists must not expose storage keys");
  const balanceBefore = (await paymentSummary(db, userId)).approvedAmount;
  assert.equal(await reviewVehicleOrder(db, userId, orderId, "approved", ""), false, "Users cannot review orders");
  assert.equal(await reviewVehicleOrder(db, adminId, orderId, "approved", "Verified"), true);
  assert.equal(await reviewVehicleOrder(db, adminId, orderId, "rejected", ""), false, "Completed order reviews cannot change");
  assert.equal((await paymentSummary(db, userId)).approvedAmount, balanceBefore, "Approving a car order never changes the plan balance");
  await db.update(schema.vehicles).set({ price: car.price + 1000, visible: false }).where(eq(schema.vehicles.id, car.id));
  assert.equal((await listUserOrders(db, userId))[0].price, car.price, "A later price change cannot alter an existing order");
  await assert.rejects(submitVehicleOrder(db, userId, { ...orderInput, id: crypto.randomUUID() }), /no longer available/, "Hidden cars cannot be ordered");
  await migrate(db, { migrationsFolder: "./migrations" });
  assert.equal((await paymentSummary(db, userId)).approvedAmount, input.amount);
  console.log("Plan payment checks passed: limits, bank transfers, car orders, unavailable wallets, stale addresses, receipt types, idempotency, admin review, account isolation, rejection/resubmission, durable balance, and receipt persistence.");
} finally { client.close(); }
