import assert from "node:assert/strict";
import { PGlite } from "@electric-sql/pglite";
import { drizzle } from "drizzle-orm/pglite";
import { migrate } from "drizzle-orm/pglite/migrator";
import { eq } from "drizzle-orm";
import * as schema from "../lib/db/schema";
import { transactPortfolio } from "../features/portfolio/service";
import { paymentSummary } from "../features/payments/plan-payment-service";
import { requestWithdrawal, reviewWithdrawal } from "../features/withdrawals/service";
import { updateUserProfit } from "../features/admin/profit-service";

const client = new PGlite();
const db = drizzle(client, { schema });
try {
  await migrate(db, { migrationsFolder: "./migrations" });
  const userId = crypto.randomUUID(), otherId = crypto.randomUUID(), adminId = crypto.randomUUID();
  for (const [id, role] of [[userId, "user"], [otherId, "user"], [adminId, "admin"]] as const) {
    await db.insert(schema.users).values({ id, role, name: role, email: `${id}@example.test`, passwordHash: "test-only", createdAt: new Date() });
  }
  const command = (command: string, args: unknown[], id = crypto.randomUUID()) => transactPortfolio(db, userId, { id, command, args });
  await assert.rejects(command("tradeStockDollars", ["TSLA", "Buy", 100]), /Verify/);
  await db.insert(schema.kycSubmissions).values({ id: crypto.randomUUID(), userId, status: "approved", legalName: "Demo User", dateOfBirth: "1990-01-01", nationality: "US", phone: "0000000000", addressLine: "Demo", city: "Demo", postalCode: "00000", country: "US", occupation: "Test", sourceOfFunds: "Test", documentType: "passport", documentLast4: "0000", documentFile: "test", selfieFile: "test", submittedAt: new Date() });
  await assert.rejects(command("tradeStockDollars", ["TSLA", "Buy", 100]), /buying power/);
  await db.insert(schema.planPayments).values({ id: crypto.randomUUID(), userId, planName: "Demo deposit", amount: 2000, methodName: "Demo", network: "Demo", address: "Demo", screenshotKey: "test-receipt", screenshotType: "image/png", status: "approved", submittedAt: new Date() });
  const stockId = crypto.randomUUID();
  await command("tradeStockDollars", ["TSLA", "Buy", 100.25], stockId);
  let summary = await paymentSummary(db, userId);
  assert.equal(summary.balanceAmount, 1899.75);
  assert.equal(summary.availableWithdrawalAmount, 1899.75);
  assert.ok(summary.portfolio.holdings.TSLA > 0);
  await command("tradeStockDollars", ["TSLA", "Buy", 100.25], stockId);
  assert.deepEqual(await paymentSummary(db, userId), summary, "A duplicate request must not debit twice");
  assert.equal((await paymentSummary(db, otherId)).balanceAmount, 0);
  assert.deepEqual((await paymentSummary(db, otherId)).portfolio.holdings, {});
  await command("tradeStockDollars", ["SPACEX", "Buy", 50.5]);
  summary = await paymentSummary(db, userId);
  assert.equal(summary.balanceAmount, 1849.25);
  assert.ok(summary.portfolio.holdings.SPACEX > 0);
  const withdrawal = { id: crypto.randomUUID(), amount: 100000, beneficiaryName: "Demo", accountNumber: "12345678", routingNumber: "000000000", bankName: "Demo", recipientAddress: "Demo", bankAddress: "Demo" };
  await requestWithdrawal(db, userId, withdrawal);
  assert.equal((await paymentSummary(db, userId)).availableWithdrawalAmount, 849.25);
  await assert.rejects(command("tradeStockDollars", ["TSLA", "Buy", 850]), /buying power/);
  await assert.rejects(requestWithdrawal(db, userId, { ...withdrawal, id: crypto.randomUUID(), amount: 85000 }), /exceeds/);
  await assert.rejects(command("sellCrypto", ["ETH", 1]), /balance/);
  await assert.rejects(command("tradeStock", ["SPACEX", "Sell", 1]), /enough shares/);
  // Crypto is closed: nothing can buy it, send it out, or start a recurring buy of it. Only Tesla and SpaceX are open.
  for (const args of [["BTC", 50], ["BTC", -1], ["unknown", 1], ["TSLA", 1]]) await assert.rejects(command("buyCrypto", args), /Only Tesla and SpaceX/);
  await assert.rejects(command("withdrawCrypto", ["BTC", 1, "bc1-demo-destination-address"]), /Only Tesla and SpaceX/);
  await assert.rejects(command("createPlan", ["asset:BTC", 25, "weekly", "BTC", null]), /Only Tesla and SpaceX/);
  await assert.rejects(command("addCash", [1000]), /Unsupported/);
  await assert.rejects(command("buyCrypto", ["BTC", 1, 0.01]), "Client cannot choose the price");
  await command("createPlan", ["foundations", 25, "weekly", null, null]);
  summary = await paymentSummary(db, userId);
  const plan = summary.portfolio.plans[0];
  assert.equal(plan.invested, 25);
  assert.equal(summary.availableWithdrawalAmount, 824.25);
  await command("processDuePlans", []);
  assert.equal((await paymentSummary(db, userId)).availableWithdrawalAmount, 824.25, "Scheduled contribution runs once");
  await command("contribute", [plan.id]);
  assert.equal((await paymentSummary(db, userId)).availableWithdrawalAmount, 799.25);
  await command("removePlan", [plan.id]);
  assert.equal((await paymentSummary(db, userId)).availableWithdrawalAmount, 849.25);
  await assert.rejects(command("removePlan", [plan.id]), /not found/);
  await command("tradeStockDollars", ["SPACEX", "Sell", 25]);
  summary = await paymentSummary(db, userId);
  assert.equal(summary.availableWithdrawalAmount, 874.25);
  await reviewWithdrawal(db, adminId, withdrawal.id, "sent", "");
  assert.equal((await paymentSummary(db, userId)).balanceAmount, summary.availableWithdrawalAmount);
  await updateUserProfit(db, adminId, { userId, expectedCents: 0, profit: 100000 });
  const beforePurchase = (await paymentSummary(db, userId)).balanceAmount;
  await command("tradeStockDollars", ["SPACEX", "Buy", 1000]);
  assert.equal((await paymentSummary(db, userId)).balanceAmount, beforePurchase - 1000);
  await assert.rejects(updateUserProfit(db, adminId, { userId, expectedCents: 100000, profit: 0 }), /purchases/);
  // Reservations were replaced by car orders: nothing can be reserved or completed any more.
  await assert.rejects(command("reserveVehicle", ["model-3-lr"]), /Unsupported/);
  await assert.rejects(command("completeGoal", ["anything"]), /Unsupported/);
  // A deposit from an earlier reservation is still refundable. Simulate one by recording it directly.
  const [holder] = await db.select().from(schema.users).where(eq(schema.users.id, userId));
  const held = JSON.parse(holder.portfolioJson!);
  held.reservations = [{ vehicleId: "model-3-lr", deposit: 1000, time: Date.now() }];
  await db.update(schema.users).set({ portfolioJson: JSON.stringify(held), portfolioSpentCents: holder.portfolioSpentCents + 100000, portfolioVersion: holder.portfolioVersion + 1 }).where(eq(schema.users.id, userId));
  const withDeposit = (await paymentSummary(db, userId)).balanceAmount;
  assert.equal(withDeposit, beforePurchase - 2000);
  await command("cancelReservation", ["model-3-lr"]);
  assert.equal((await paymentSummary(db, userId)).balanceAmount, withDeposit + 1000);
  await assert.rejects(command("cancelReservation", ["model-3-lr"]), /not found/);
  await client.exec("CREATE OR REPLACE FUNCTION fail_trade_audit() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'rollback'; END $$; CREATE TRIGGER fail_trade_audit BEFORE INSERT ON audit_log FOR EACH ROW WHEN (NEW.action LIKE 'portfolio.%') EXECUTE FUNCTION fail_trade_audit();");
  const beforeFailure = await paymentSummary(db, userId);
  await assert.rejects(command("tradeStockDollars", ["TSLA", "Buy", 25]));
  assert.deepEqual(await paymentSummary(db, userId), beforeFailure, "Audit failure rolls back holdings and cash together");
  await client.exec("DROP TRIGGER fail_trade_audit ON audit_log");
  await db.update(schema.users).set({ status: "suspended" }).where(eq(schema.users.id, userId));
  await assert.rejects(command("tradeStockDollars", ["TSLA", "Buy", 25]), /unavailable/);
  await migrate(db, { migrationsFolder: "./migrations" });
  assert.deepEqual(await paymentSummary(db, userId), beforeFailure, "Saved holdings survive repeated initialization");
  console.log("Portfolio checks passed: deposit-funded purchases, stocks and crypto, exact cents, user isolation, duplicate requests, server prices, overspending, withdrawal reserves, sales, recurring plans, reservations/refunds, profit coverage, authorization, persistence, atomic rollback.");
} finally { client.close(); }
